version: "3.9"

services:

  worker:
    build: .
    depends_on:
      - "redis"
    command:
      - /bin/sh
      - -c
      - |
         python worker-client.py
    deploy:
      replicas: 15
    restart: on-failure
    environment:
      REDIS_URL: redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: on-failure