version: "3.9"
services:
  coordinator:
    build: .
    depends_on:
      - "redis"
    command:
      - /bin/sh
      - -c
      - |
         python server-coordinator.py
  worker:
    build: .
    depends_on:
      - "coordinator"
      - "redis"
    command:
      - /bin/sh
      - -c
      - |
         python worker-client.py
    deploy:
      replicas: 5
  redis:
    image: "redis:alpine"